name: Package-x64

on:
  push:
    branches: [ main ]
    paths-ignore: [README.md]
  pull_request:
    branches: [ main ]
    paths-ignore: [README.md]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt -y install build-essential
          
      - name: Configure
        run: |
          cd C-edition
          mkdir build
          
      - name: Build
        run: |
          cd C-edition/build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make -j4
          make package
          echo "PKG_NAME=$(ls | grep aptpac*Linux*.sh)" >> $GITHUB_ENV

      - name: gen-date
        run: echo "DATE=$(date +"%F")" >> $GITHUB_ENV
        
  
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: aptpac_package_x64_${{ env.DATE }}
          path: C-edition/build/${{ env.PKG_NAME }}
