name: Package-arm64

on:
  push:
    branches: [ main ]
    paths-ignore: [README.md]
  pull_request:
    branches: [ main ]
    paths-ignore: [README.md]
    
jobs:
  build-arm64:
    runs-on: ubuntu-22.04-arm
    name: Build-arm64 
    steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: package
          run: |
            DEBIAN_FRONTEND=noninteractive apt update
            DEBIAN_FRONTEND=noninteractive apt install build-essential cmake gcc make -y
            cd C-edition/
            mkdir build
            cd build
            cmake -DCMAKE_BUILD_TYPE=Release ..
            make -j$(nproc)
            make package

        - name: gen-pkgname
          run: |
              cd C-edition/build
              echo "PKG_NAME=$(ls | grep aptpac*Linux*.sh)" >> $GITHUB_ENV
        - name: gen-date
          run: echo "DATE=$(date +"%F")" >> $GITHUB_E
        - name: upload
          uses: actions/upload-artifact@v4
          with:
              name: aptpac_package_arm64_${{ env.DATE }}
              path: C-edition/build/${{ env.PKG_NAME }}/
