name: Build-arm64

on:
  push:
    branches: [ main ]
    paths-ignore: [README.md]
  pull_request:
    branches: [ main ]
    paths-ignore: [README.md]
    
jobs:
  build-arm64:
    runs-on: ubuntu-latest
    name: Build-arm64 
    steps:
      - uses: actions/checkout@v2
      - uses: darsvador/run-on-arch-action@v1.0.10
        with:
          architecture: aarch64
          distribution: ubuntu20.04
          run: |
            DEBIAN_FRONTEND=noninteractive apt update
            DEBIAN_FRONTEND=noninteractive apt install build-essential cmake gcc make -y
            cd C-edition/
            mkdir build
            cd build
            cmake -DCMAKE_BUILD_TYPE=Release ..
            make -j$(nproc)
            make package
            echo "PKG_NAME=$(ls | grep aptpac*Linux*.sh)" >> $GITHUB_ENV
            
      - name: gen-date
        run: echo "DATE=$(date +"%F")" >> $GITHUB_ENV
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: aptpac_package_arm64_${{ env.DATE }}
          path: C-edition/build/${{ env.PKG_NAME }}/
