name: publish-x64
on:
  release:
    types:
      - created
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          DEBIAN_FRONTEND=noninteractive sudo apt update
          DEBIAN_FRONTEND=noninteractive sudo apt -y install build-essential
      - name: Configure
        run: |
          mkdir C-edition/build
          cd C-edition/build
          cmake -DCMAKE_BUILD_TYPE=Release ..
      - name: Build
        run: |
          cd C-edition/build
          make
      - name: Package
        run: |
          cd C-edition/build
          cpack -G STGZ
          echo "PKG=$(basename *.sh)" >> $GITHUB_ENV
      - name: Upload to release
        uses: gacts/upload-to-release@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: 'C-edition/build/${{ env.PKG }}'
          type: 'text/x-shellscript'
