name: CMake

on:
  release:
    types:
      - created

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Package
      run: |
        cd ${{github.workspace}}/build
        cpack -G STGZ
        echo "PKG=$(basename *.sh)" >> $GITHUB_ENV
    - name: Upload to release
      uses: gacts/upload-to-release@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: 'build/${{ env.PKG }}'
        type: 'text/x-shellscript'
      
