name: Release

on:
  release:
    types:
      - created
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: |
        cd aptpac/C-edition/
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..

    - name: Build
      run: make -C C-edition/build

    - name: Package
      run: |
        cd C-edition/build
        cpack -G STGZ
        echo "PKG=$(basename *.sh)" >> $GITHUB_ENV
    - name: Upload to release
      uses: gacts/upload-to-release@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: 'C-edition/build/${{ env.PKG }}'
        type: 'text/x-shellscript'
      
